template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "inar1241"
__REPO__ = "lang-smn"
__UND2C__ = "smn"
__UNDEFINED__ = "Inari Sami"
__UND__ = "smn"
