[package]
name = "smn"
human_name = "Inari Sami"
version = "1.0.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.smn]
filename = "smn-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-smn"
platform = "windows"
uuid = "BD03C81C-6B96-49C2-AD34-FE93AD1F911A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.smn"
package = "speller-smn"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-smn-mso"
platform = "windows"
uuid = "C0DFE889-8368-451B-B169-422498A97D2A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-smn"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
