name: Build in-code documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # can change this to 2.7 or whatever version you prefer
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v2
        with:
          repository: giellalt/giella-shared
          path: giella-shared
      - uses: actions/checkout@v2
        with:
          path: lang
      - name: Install dev dependencies
        uses: divvun/actions/lang/install-deps@master
        with:
          sudo: true
      - name: Build giella-core/giella-shared
        uses: divvun/actions/lang/build@master
        with:
          spellers: false
          fst: hfst
      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: lang/docs/
      - name: 🚀 deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lang/docs/
          enable_jekyll: true
